nelmio_api_doc:
    documentation:
        info:
            title: Projects Manager
            description: This api is used to see and manage projects
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - /api(?!/doc$) # Accepts routes under /api except /api/doc
            - /workers?
            - /projects?
            - /keywords?
            - /models
    models:
        use_jms: true
    


        
