


app_project_get_projects:
    path: /projects
    controller: App\Controller\ProjectController::GetProjects
    methods: GET
    

app_workers:
    path: /workers
    controller: App\Controller\WorkerController::GetWorkers
    methods: GET


app_keywords:
    path: /keywords
    controller: App\Controller\KeywordsController::GetKeywords
    methods: GET

app_keywordsObjects:
    path: /keywordsObjects
    controller: App\Controller\KeywordsController::GetObjects
    methods: GET
