# /path

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_project:
    path: /project
    controller: App\Controller\ProjectController::Get
    methods: GET

